### ISSUE TITLE
Brakuje konstruktora przyjmującego M i N

### ISSUE THREAD

**Issue by ziobron** [bogkra/divisors#1]
Uzależnianie funkcji od operacji wejścia jak wczytywanie z cin w funkcjach inN i inM nie jest dobrym pomysłem. Stan obiektu powinien być od samego początku ustalony za pomocą konstruktora

**Comment by ziobron** [comment]
Niby zamknięte ale konstruktora dalej nie widać

**Comment by bogkra** [comment]
jest int N = 0 , M = 0;

**Comment by ziobron** [comment]
A jak będziesz chciał ustawić coś innego niż 0 i 0?
